version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.7.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: ./bin/build.js
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: test
          create-repo: true
          dockerfile: Dockerfile
          path: Dockerfile
          repo: strapi
          tag: 'latest'
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - build_and_push_image
