version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.7.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - setup_remote_docker
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - aws-ecr/build-and-push-image:
            context: test
            repo: strapi
